version: '3'
services:
  nginx:
    build: ./nginx
    depends_on:
      - php
      - hyperf
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/error.log:/var/log/nginx/error.log
    #networks:
    #  - frontend
    restart: always
    container_name: nginx

  php:
    build: ./php
    volumes:
      - ./www:/var/www/html
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
      - ./php/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/config/php-fpm.d:/usr/local/etc/php-fpm.d
    #command: ["php", "/var/www/html/bjkgg/bin/m-httpd","service", "start","d"]
    #networks:
    #  - frontend
    #  - backend
    #ports:
    #  - "9501:9501"
    restart: always
    container_name: php
    
  hyperf:
    build: ./hyperf/7.3
    volumes:
      - ./www:/opt/www
    #  - ./hyperf/7.2/config/php.ini:/etc/php7/php.ini
      #command: ["php", "/var/www/html/bjkgg/bin/m-httpd","service", "start","d"]
    stdin_open: true
    tty: true
    #networks:
    #  - frontend
    #  - backend
    ports:
      - "9501:9501"
      - "9502:9502"
    restart: always
    container_name: hyperf

  mysql:
    build: ./mysql57
    command: --innodb-use-native-aio=0
    ports:
      - "3307:3306"
    volumes:
      - ./mysql57/data:/var/lib/mysql
      - ./mysql57/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    #networks:
    #  - backend
    restart: always
    container_name: mysql

  redis:
    build: ./redis
    ports:
      - "6380:6379"
    volumes:
      - ./redis/redis.conf/:/usr/local/etc/redis.conf
      - ./redis/data:/usr/local/redis/data
      - ./redis/redis.log:/usr/local/redis/redis.log
    #networks:
    #  - backend
    restart: always
    container_name: redis

  rabbitmq:
    build: ./rabbitmq
    hostname: my_rabbit
    ports:
      #- "25672:25672"
      - "15672:15672"
      #- "15671:15671"
      - "5672:5672"
      #- "5671:5671"
      #- "4369:4369"
    environment:
      #- RABBITMQ_ERLANG_COOKIE=rabbitmqCookie
      #- RABBITMQ_DEFAULT_VHOST=itet
      - RABBITMQ_DEFAULT_USER=adm
      - RABBITMQ_DEFAULT_PASS=adm
    volumes:
      #- ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq/log
    #command: ["chmod", "600","/var/lib/rabbitmq/.erlang.cookie"]
    #networks:
    #  - backend
    restart: always
    container_name: rabbitmq

networks:
  #frontend:
  #backend:
  default:
    external:
      name: elk_elknet
